# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Pay-As-You-Go(5b586977-f8bb-4da6-a6ae-1c9d07790eef)'

  # Web app name
  webAppName: 'biofuture-uat-web'

  # Environment name
  environmentName: 'biofuture-uat-web'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)



    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        #npm install -g serve
        #npm install
        yarn install
        #npm run build
      displayName: 'npm install and build '
      
    
    - script: 
        npm run build
        #yarn build
      displayName: 'npm build'
      
    
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)/build' 
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        cleanTargetFolder: true
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              Action: 'Stop Azure App Service'
              WebAppName: $(webAppName)
          
          
          # - task: AzureRmWebAppDeployment@4
          #   displayName: 'Azure App Service Deploy: $(webAppName)'
          #   inputs:
          #     azureSubscription: $(azureSubscription)
          #     appType: webAppLinux
          #     WebAppName: $(webAppName)
          #     RuntimeStack: 'NODE|14-lts'
          #     package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
          #     StartupCommand: 'npx serve -s'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pay-As-You-Go(5b586977-f8bb-4da6-a6ae-1c9d07790eef)'
              appType: 'webAppLinux'
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              RuntimeStack: 'NODE|14-lts'
              StartupCommand: 'npx serve -s'
          
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              Action: 'Start Azure App Service'
              WebAppName: $(webAppName)