export const {
  CREATE,
  EDIT,
  DELETE,
  ACTIVATE,
  DEACTIVATE,
  APPROVE,
  CONFIRM,
  DOWNLOAD,
  REJECT,
} = {
  CREATE: "CREATE",
  EDIT: "EDIT",
  DELETE: "DELETE",
  ACTIVATE: "ACTIVATE",
  DEACTIVATE: "DEACTIVATE",
  APPROVE: "APPROVE",
  CONFIRM: "CONFIRM",
  DOWNLOAD: "DOWNLOAD",
  REJECT: "REJECT",
};

export const { ALL, PENDING, REJECTED, APPROVED, CONFIRMED } = {
  ALL: "ALL",
  PENDING: "PENDING",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
  CONFIRMED: "CONFIRMED",
};

export const {
  USERS,
  ROLES,
  CUSTOMERS,
  CONTRACTS,
  QUOTES,
  INVOICES,
  JOB_ORDERS,
  SETS_REMARKS,
  SETS_PAYMENT_METHODS,
  SETS_SERVICES,
  SETS_TERMS_CONDITIONS,
  REPORTS,
} = {
  USERS: "USERS",
  ROLES: "ROLES",
  CUSTOMERS: "CUSTOMERS",
  CONTRACTS: "CONTRACTS",
  QUOTES: "QUOTES",
  INVOICES: "INVOICES",
  JOB_ORDERS: "JOB_ORDERS",
  SETS_REMARKS: "SETS_REMARKS",
  SETS_PAYMENT_METHODS: "SETS_PAYMENT_METHODS",
  SETS_SERVICES: "SETS_SERVICES",
  SETS_TERMS_CONDITIONS: "SETS_TERMS_CONDITIONS",
  REPORTS: "REPORTS",
};

export const modules = [
  {
    name: "Customer (Dashboard)",
    code: "CUSTOMER_DASHBOARD",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Coming End Contract (Dashboard)",
    code: "COMING_AND_CONTRACT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "New Users (Dashboard)",
    code: "NEW_USER",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Sales Business (Dashboard)",
    code: "SALES_BUSINESS",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Future Job Order Quantity (Dashboard)",
    code: "FUTURE_JOB_ORDER_QUANTITY",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Items Sales Stat (Dashboard)",
    code: "ITEMS_SALES_STAT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Overdue Amount (Dashboard)",
    code: "OVERDUE_AMOUNT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Sales Performance Stats (Dashboard)",
    code: "SALES_PERFORMANCE_STATS",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Upload Document Reminder (Dashboard)",
    code: "UPLOAD_DOCUMENT_REMINDER",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Create Job Reminder (Dashboard)",
    code: "CREATE_JOB_REMINDER",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Business Source (Dashboard)",
    code: "BUSINESS_SOURCE",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "User",
    code: "USER",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Role",
    code: "ROLE",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Customer",
    code: "CUSTOMER",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Quotation",
    code: "QUOTATION",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: true,
    confirm: true,
  },
  {
    name: 'Quotation Details page sales Remark',
    code: 'QUOTATION_DETAILS_SALES_REMARK',
    read: true,
    add: true,
    edit: false,
    delete: true,
    approve_reject: false,
    confirm: false
  },
  {
    name: 'Contract',
    code: 'CONTRACT',
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: true,
    confirm: true,
  },
  {
    name: 'Contract Details page sales Remark',
    code: 'CONTRACT_DETAILS_SALES_REMARK',
    read: true,
    add: true,
    edit: false,
    delete: true,
    approve_reject: false,
    confirm: false
  },
  {
    name: 'Job',
    code: 'JOB',
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: true,
    confirm: false,
  },
  {
    name: "Invoice",
    code: "INVOICE",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: true,
    confirm: true,
  },
  {
    name: "Payment Item",
    code: "PAYMENT_ITEM",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Remark",
    code: "REMARK",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Service Item",
    code: "SERVICE_ITEM",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Terms and Condition",
    code: "TERMS_AND_CONDITION",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Teams",
    code: "TEAMS",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Districts",
    code: "DISTRICTS",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Commercial Sector",
    code: "COMMERCIAL_SECTOR",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Reject Reason",
    code: "REJECT_REASON",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Termination Reason",
    code: "TERMINATION_REASON",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Question",
    code: "QUESTION",
    read: true,
    add: true,
    edit: true,
    delete: true,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Contract Invoice (Report)",
    code: "CONTRACT_INVOICE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Pending Invoice (Report)",
    code: "PENDING_INVOICE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Quotation Invoice (Report)",
    code: "QUOTATION_INVOICE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "New Customer (Report)",
    code: "NEW_CUSTOMER_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Sales Business (Report)",
    code: "SALES_BUSINESS_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Items Sales Stat (Report)",
    code: "ITEMS_SALES_STAT_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Contract End (Report)",
    code: "COMMING_END_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Overdue Amount (Report)",
    code: "OVERDUE_AMOUNT_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Future Job Order (Report)",
    code: "FUTURE_JOB_ORDER_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Sales Performance (Report)",
    code: "SALES_PERFORMANCE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Client Rejected (Report)",
    code: "CLIENT_REJECTED",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Terminated Contract (Report)",
    code: "TERMINATED_CONTRACT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Customer (Report)",
    code: "CUSTOMER_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Upload Document (Report)",
    code: "UPLOAD_DOCUMENT_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Service Item (Report)",
    code: "SERVICE_ITEM_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Unfinished Job (Report)",
    code: "UNFINISHED_JOB_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Customer Referrals (Report)",
    code: "CUSTOMER_REFERRALS",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Business Source (Report)",
    code: "BUSINESS_SOURCE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Sales Invoice (Report)",
    code: "SALES_INVOICE_REPORT",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Customer Officer",
    code: "CUSTOMER_OFFICER",
    read: false,
    add: false,
    edit: true,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Show All Customer Data",
    code: "SHOW_ALL_CUSTOMER_DATA",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Waiting Arrangement Job (Calender)",
    code: "WAITING_ARRANGEMENT_JOB_CALENDER",
    read: true,
    add: false,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Drag to assign job order",
    code: "DRAG_TO_ASSIGN_JOB_ORDER",
    read: false,
    add: false,
    edit: true,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Create more job order",
    code: "CREATE_MORE_JOB_ORDER",
    read: false,
    add: true,
    edit: false,
    delete: false,
    approve_reject: false,
    confirm: false,
  },
  {
    name: "Special Edit",
    code: "SPECIAL_EDIT",
    read: false,
    add: false,
    edit: true,
    delete: false,
    approve_reject: true,
    confirm: false,
  },
  {
    name:"App Login",
    code:"APP_LOGIN",
    read: false,
    add: false,
    edit: false,
    delete: false,
    approve_reject: true,
    confirm: false,
  }
];

// export const modules = {
//   USERS: "USERS",
//   ROLES: "ROLES",
//   CUSTOMERS: "CUSTOMERS",
//   CONTRACTS: "CONTRACTS",
//   QUOTES: "QUOTES",
//   INVOICES: "INVOICES",
//   JOB_ORDERS: "JOB_ORDERS",
//   SETS_REMARKS: "SETS_REMARKS",
//   SETS_PAYMENT_METHODS: "SETS_PAYMENT_METHODS",
//   SETS_SERVICES: "SETS_SERVICES",
//   SETS_TERMS_CONDITIONS: "SETS_TERMS_CONDITIONS",
//   REPORTS: "REPORTS",
// };
